services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "443:80"
    volumes:
        - type: bind
          source: /etc/letsencrypt/archive/savagepastaman.com
          target: /etc/ssl/
    tty: true
    environment:
      - RUST_LOG=error
      - ROCKET_TLS={certs=/etc/ssl/fullchain1.pem,key=/etc/ssl/privkey1.pem}