version: "3.9"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

services:
  blog:
    <<: *logging

  prometheus:
    image: prom/prometheus:2.36.0
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    depends_on:
      - app

  grafana:
    image: grafana/grafana-oss:8.2.0
    ports:
      - "3000:3000"
