FROM rust:1.54 as base

RUN USER=root cargo new --bin blog
WORKDIR /blog

COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

RUN rustup component add clippy

RUN cargo build
RUN rm src/*.rs

COPY src src

RUN rm target/debug/deps/blog*

RUN cargo build
RUN cargo clippy -p blog -- --no-deps -D clippy::all

FROM debian:buster-slim as dev

COPY --from=base /blog/target/debug/blog ./app

COPY Rocket.toml Rocket.toml
COPY images /blog/images
COPY fonts /blog/fonts
COPY styles /blog/styles

CMD ["./app"]

EXPOSE 8000
