services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "8000:80"
    tty: true
    volumes:
      - type: bind
        source: ./articles/md
        target: /articles/md
      - type: bind
        source: ./templates
        target: /templates
      - type: bind
        source: ./styles
        target: /blog/styles
    restart: on-failure
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=trace,handlebars=info

#  grafana:
#    image: grafana/grafana-oss:8.2.0
#    ports:
#      - "3000:3000"