name: push-articles
on:
  push:
#    branches:
#      - master
    paths:
      - 'articles/**'
jobs:
  push-articles:
    runs-on: ubuntu-latest
    steps:
        - id: install-aws-cli
          uses: unfor19/install-aws-cli-action@v1.0.3
        - run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - run: aws configure set region us-east-1
        - run: echo aws lightsail get-container-images